apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: lab5-app
type: Opaque
data:
  # rootpassword
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  # appuser
  MYSQL_USER: YXBwdXNlcg==
  # apppassword
  MYSQL_PASSWORD: YXBwcGFzc3dvcmQ=
  # apppassword (for web app)
  DB_PASSWORD: YXBwcGFzc3dvcmQ=
  # appuser (for web app)
  DB_USER: YXBwdXNlcg==
