apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: lab5-app
type: Opaque
data:
  # appuser
  POSTGRES_USER: YXBwdXNlcg==
  # apppassword
  POSTGRES_PASSWORD: YXBwcGFzc3dvcmQ=
  # apppassword (for web app)
  DB_PASSWORD: YXBwcGFzc3dvcmQ=
  # appuser (for web app)
  DB_USER: YXBwdXNlcg==
