apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: final-exam
type: Opaque
data:
  # mongo-user: admin
  MONGO_USER: YWRtaW4=
  # mongo-password: MongoP@ss2025
  MONGO_PASSWORD: TW9uZ29QQHNzMjAyNQ==
