apiVersion: v1
kind: Secret
metadata:
  name: backend-api-secret
  namespace: final-exam
type: Opaque
data:
  # db-user: admin
  DB_USER: YWRtaW4=
  # db-password: PostgresP@ss2025
  DB_PASSWORD: UG9zdGdyZXNQQHNzMjAyNQ==
