apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: final-exam
type: Opaque
data:
  # mongodb-root-username: admin
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  # mongodb-root-password: MongoP@ss2025
  MONGO_INITDB_ROOT_PASSWORD: TW9uZ29QQXNZMJAY1
