apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: final-exam
type: Opaque
data:
  # postgres-user: admin
  POSTGRES_USER: YWRtaW4=
  # postgres-password: PostgresP@ss2025
  POSTGRES_PASSWORD: UG9zdGdyZXNQQHNzMjAyNQ==
