apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: three-tier-app
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "taskdb"
  PORT: "5000"
  NODE_ENV: "production"
