apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: three-tier-app
type: Opaque
data:
  # taskuser (base64)
  POSTGRES_USER: dGFza3VzZXI=
  # SecureP@ss123 (base64)
  POSTGRES_PASSWORD: U2VjdXJlUEBzczEyMw==
